from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm


def create_worksheet_pdf(
    worksheet: dict,
    output_path: str,
):

    pdf = canvas.Canvas(
        output_path,
        pagesize=A4,
    )

    width, height = A4

    margin = 20 * mm

    y = height - margin

    # Header
    pdf.setFont(
        "Helvetica-Bold",
        18,
    )

    pdf.drawString(
        margin,
        y,
        "TRIBAL LINGUA AI",
    )

    y -= 12 * mm

    pdf.setFont(
        "Helvetica-Bold",
        14,
    )

    pdf.drawString(
        margin,
        y,
        "Bilingual Learning Worksheet",
    )

    y -= 15 * mm

    # Learning outcome
    pdf.setFont(
        "Helvetica-Bold",
        11,
    )

    pdf.drawString(
        margin,
        y,
        "Learning Outcome",
    )

    y -= 7 * mm

    pdf.setFont(
        "Helvetica",
        10,
    )

    pdf.drawString(
        margin,
        y,
        worksheet[
            "learning_outcome"
        ]["hindi"],
    )

    y -= 10 * mm

    # Questions
    pdf.setFont(
        "Helvetica-Bold",
        12,
    )

    pdf.drawString(
        margin,
        y,
        "Questions",
    )

    y -= 10 * mm

    for question in worksheet["questions"]:

        pdf.setFont(
            "Helvetica-Bold",
            11,
        )

        pdf.drawString(
            margin,
            y,
            f"{question['number']}.",
        )

        pdf.setFont(
            "Helvetica",
            10,
        )

        pdf.drawString(
            margin + 8 * mm,
            y,
            question["hindi"],
        )

        y -= 7 * mm

        pdf.setFont(
            "Helvetica-Oblique",
            9,
        )

        pdf.drawString(
            margin + 8 * mm,
            y,
            "Santali:",
        )

        y -= 8 * mm

        # Answer area
        pdf.line(
            margin + 8 * mm,
            y,
            width - margin,
            y,
        )

        y -= 15 * mm

        if y < margin + 25 * mm:

            pdf.showPage()

            y = height - margin

    pdf.setFont(
        "Helvetica",
        8,
    )

    pdf.drawString(
        margin,
        10 * mm,
        "Generated by Tribal Lingua AI",
    )

    pdf.save()
